name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cabal: ["3.2"]
        ghc:
          - "8.6.5"
          - "8.8.3"
          - "8.10.1"
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-haskell@v1.1
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v1
      name: Cache cabal-store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: Install system dependencies
      run: |
        sudo apt-get install libsqlite3-dev

    - name: Build dependencies
      run: |
        cabal update
        cabal build all --enable-tests --enable-benchmarks -j --dep

    - name: Build sqroll
      run: cabal build all -j

    - name: Test
      run: |
        cabal test all --enable-tests
